# Website generator in Jekyll

name: Showbiz
title: Orgulhosamente Falando de Música
email: showbiz@showbiz.mus.br
description: O Showbiz é um site para músicos buscar partituras e estudos musicais na qual as pessoas precisam conhecer mais sobre música. Faça parte você também.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: showbizmus
youtube_username:  canalshowbiz
pintrest_username: showbizmusbr
facebook_username: showbizmus
author: Showbiz.mus.br
author_url: marviorocha.com
production: false

mailchimp-list: https://mus.us13.list-manage.com/subscribe/post?u=4c6278e721e4ae538e1ef5fde&amp;id=923ffebb4a


copyright: Todos os direitos reservados

# Build settings
theme: minima
plugins:
  - jekyll-feed

disqus:
  shortname: showbizmus

algolia:
  application_id: '34RV5PG28H'
  index_name:

collections:
  pages:
    output: true


  # Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
